### ISSUE TITLE
Update tutor.ja

### ISSUE THREAD

**Issue by crazymaster** [vim-jp/vimdoc-ja#107]
- 最新への追従
- typoの修正

**Comment by mattn** [comment]
いまさらだけど確認しました。
変える程の内容ではないし、漢字とカタカナが混じっている方が w をタイプした時に文字クラスで止まってくれて初心者の理解としては良いと思いました。
なので僕としては直さないでいいかなと思います。

**Comment by k-takata** [comment]
tutorは、lang-jaに移ったことですし、閉じてよい？

**Comment by crazymaster** [comment]
何かあればlang-jaの方へissueを立てるということで

**Comment by crazymaster** [comment]
> どこの Andre さん?

前に貼ったvim_devのスレの人です
