### ISSUE TITLE
:help starの2.と4.誤訳

### ISSUE THREAD

**Issue by h-east** [vim-jp/vimdoc-ja#117]
原文
```
				1. the keyword under the cursor |'iskeyword'|
				2. the first keyword after the cursor, in the
				   current line
				3. the non-blank word under the cursor
				4. the first non-blank word after the cursor,
				   in the current line
```
日本語訳
```
				1. カーソル位置のキーワード |'iskeyword'|
				2. 現在行の、カーソルの前方のキーワード
				3. カーソル位置の単語 (|WORD|)
				4. 現在行の、カーソルの前方の単語
```
`2.`と`4.`が逆ですよね
。
修正案
```
				2. 現在行の、カーソルの後ろの最初のキーワード
				4. 現在行の、カーソルの後ろの最初の単語
```

どうでしょうか？

**Comment by ynkdir** [comment]
そこはたぶん前方検索/後方検索という文脈で前方/後方で合わせてるので大丈夫と思います。
カーソルの前/後、前方/後方ってどっちがどっちか文脈によってもちがうんでしょうけどよくわからなくて、場所によって前/後を逆の意味に書いたところがけっこうあった気がします。
どっちがいいかはわからないです。

**Comment by h-east** [comment]
遅レスすまそ。
英語はforward/backwardとbefore/afterで説明してあるけど特に分かり難いと感じなかったです。(もう知ってるからかもですが)
日本語訳の方も素直に訳した方が良いと思います。
`:h star@ja`と`:h star@en`を見比べて「誤訳では？」と思った人が私以外に少なくとも1人はいらっしゃいました。

**Comment by h-east** [comment]
forward → 前方
backward → 後方
before the ～ → ～の前
after the ～ → ～の後ろ

「forward/backwardの訳は前方/後方で固定、before/afterの訳には前方/後方を使用しない」というポリシーですっきりする気がするんですがいかがでしょうか？

**Comment by ynkdir** [comment]
いいと思います。

**Comment by h-east** [comment]
`:helpgrep [前後]方\(互換\)\@!`して明らかにそぐわない訳をピックアップしてみました。
```
index.jax|540 col 48| |CTRL-W_R|	CTRL-W R	   ウィンドウ位置を後方へ N 回転させる。
```
「ウィンドウ位置を上向きにN回転させる。」がいいと思う。
```
index.jax|589 col 48| |CTRL-W_r|	CTRL-W r	   ウィンドウ位置を後方へ N 回転させる。
```
逆だｗ。「ウィンドウ位置を下向きにN回転させる。」がいいと思う。

**Comment by h-east** [comment]
特に反対意見がないようなので、
本Issue本文の`:help star`の`2.`と`4.`と、1つ前のコメントの`CTRL-W_R`と`CTRL-W_r`の訳を今週末修正します。

**Comment by h-east** [comment]
Vim ドキュメント翻訳者の手引き に下記2行を追加しようと思います。意見あれば4/11(土)夕方までにコメントください。
https://github.com/vim-jp/vimdoc-ja/wiki/Guide

- forward/backword → 前方/後方 固定とする。
- before/after → 前/後ろ (前方/後方 と訳さない)

**Comment by thinca** [comment]
:+1:

**Comment by presuku** [comment]
:+1:

@h-east 
tweetを拾って、issueの登録ありがとうございました。
vim-jpの方ばかりみてて、こちらに気づくの遅れました…

また、その後に気づいたのですが、`:help search-range`の説明だと
```
...snip...
The "*", "#", "g*" and "g#" commands look for a word near the cursor in this
order, the first one that is found is used:
- The keyword currently under the cursor.
- The first keyword to the right of the cursor, in the same line.
- The WORD currently under the cursor.
- The first WORD to the right of the cursor, in the same line.
...snip...
```
の様に、カーソルの右となっていて、その他も含め微妙に文章が異なるのですね。

**Comment by h-east** [comment]
Done.

@presuku 右/左で統一されていたら迷わないんですけどね。たぶん、`before/after`が多い気がします。
