### ISSUE TITLE
autocmd の誤訳など

### ISSUE THREAD

**Issue by ichizok** [vim-jp/vimdoc-ja#119]
**`BufNew`**
https://github.com/vim-jp/vimdoc-ja/blob/6e8af251ee/doc/autocmd.jax#L392
誤: `解放されるバッファ`
正: `作成されるバッファ`

**`FileChangedShell`**
https://github.com/vim-jp/vimdoc-ja/blob/6e8af251ee/doc/autocmd.jax#L604
誤: `解放されるバッファ`
正?: `変更されたバッファ`
(原文: `buffer that was changed`)

**`BufDelete`, `BufHidden`, `BufUnload`, `BufWinLeave`, `BufWipeout`**
https://github.com/vim-jp/vimdoc-ja/blob/6e8af251ee/doc/autocmd.jax#L356
https://github.com/vim-jp/vimdoc-ja/blob/6e8af251ee/doc/autocmd.jax#L379
https://github.com/vim-jp/vimdoc-ja/blob/6e8af251ee/doc/autocmd.jax#L425
https://github.com/vim-jp/vimdoc-ja/blob/6e8af251ee/doc/autocmd.jax#L450
https://github.com/vim-jp/vimdoc-ja/blob/6e8af251ee/doc/autocmd.jax#L465
全て `解放されるバッファ` と表現されていますが、原文ではそれぞれ
(being) `deleted`, `unloaded`, `unloaded`, `unloaded`, `deleted` となっています。
* `BufDelete`, `BufWipeout` については `削除されるバッファ` が適切かと思います。  
* `BufHidden`, `BufWinLeave` を、`BufUnload` と同じ `解放されるバッファ` とするのは違和感あります。 (原文でも同じ `unloaded` ですが...)

**Comment by mattn** [comment]
解放感ある

On 4/4/15, ichizok <notifications@github.com> wrote:
> **`BufNew`**
> https://github.com/vim-jp/vimdoc-ja/blob/6e8af251ee/doc/autocmd.jax#L392
> 誤: `解放されるバッファ`
> 正: `作成されるバッファ`
>
> **`FileChangedShell`**
> https://github.com/vim-jp/vimdoc-ja/blob/6e8af251ee/doc/autocmd.jax#L604
> 誤: `解放されるバッファ`
> 正?: `変更されたバッファ`
> (原文: `buffer that was changed`)
>
> **`BufDelete`, `BufHidden`, `BufUnload`, `BufWinLeave`, `BufWipeout`**
> https://github.com/vim-jp/vimdoc-ja/blob/6e8af251ee/doc/autocmd.jax#L356
> https://github.com/vim-jp/vimdoc-ja/blob/6e8af251ee/doc/autocmd.jax#L379
> https://github.com/vim-jp/vimdoc-ja/blob/6e8af251ee/doc/autocmd.jax#L425
> https://github.com/vim-jp/vimdoc-ja/blob/6e8af251ee/doc/autocmd.jax#L450
> https://github.com/vim-jp/vimdoc-ja/blob/6e8af251ee/doc/autocmd.jax#L465
> 全て `解放されるバッファ` と表現されていますが、原文ではそれぞれ
> (being) `deleted`, `unloaded`, `unloaded`, `unloaded`, `deleted` となっています。
> * `BufDelete`, `BufWipeout` については `削除されるバッファ` が適切かと思います。
> * `BufHidden`, `BufWinLeave` を、`BufUnload` と同じ `解放されるバッファ` とするのは違和感あります。
> (原文でも同じ `unloaded` ですが...)
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/vimdoc-ja/issues/119


-- 
- Yasuhiro Matsumoto

**Comment by h-east** [comment]
@ichizok Nice! :+1: 

LGTM
修正お願い出来ますか？

> BufHidden, BufWinLeave を、BufUnload と同じ 解放されるバッファ とするのは違和感あります。 (原文でも同じ unloaded ですが...)

そのままにするか、原文&日本語訳を修正するかはお任せします。
(原文の変更はもちろんvim_devへpatch送付という形になります)

**Comment by h-east** [comment]
ご存知だと思いますが、develブランチに対して作業するのをお忘れなく
https://github.com/vim-jp/vimdoc-ja/wiki/Workflow#%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E3%81%AE%E8%AA%AC%E6%98%8E

**Comment by ichizok** [comment]
#120 投げました。
`BufHidden`, `BufWinLeave` についてはひとまず置いておきます。

@h-east あぶないところでした。

**Comment by h-east** [comment]
Merged.
