### ISSUE TITLE
Operator-pending modeの訳をオペレータ待機モードに統一したい

### ISSUE THREAD

**Issue by h-east** [vim-jp/vimdoc-ja#123]
Vimのモードの1つである`Operator-pending mode`の訳が現在2種類あります。
- オペレータ待機モード (map.jax以外)
- 演算待ち状態モード (map.jax)

どうも`演算待ち状態モード`がしっくり来ないと言うか本来のものの意味を表していない感じを受けます。

提案: 
`Operator-pending mode`の訳を`オペレータ待機モード`に統一しませんか？

特に反対意見がなければ次の日曜(4/26)に修正します。

**Comment by k-takata** [comment]
#58 で放置していた件ですね。

**Comment by h-east** [comment]
@k-takata あっ:sweat_smile:、既出だったんですね。Thanks!

> Operator-pendingについては、演算待ち状態、オペレータ待機、モーション待ち、演算子未解決、などの訳がありましたが、何が適切かよく分かりません。

こ、こんなに...

でもやっぱり`オペレータ待機モード`でいいんじゃないですかねー。

**Comment by h-east** [comment]
とりあえずmap.jaxだけ `:%s/演算待ち状態/オペレータ待機/g` しました。
https://github.com/vim-jp/vimdoc-ja/commit/dce884dfc934844a351aa7dd682a97a7a3854fcb

**Comment by h-east** [comment]
操作としての `operator` が`演算コマンド`となっているところがありますが`オペレータ`に統一しようとしています。(作業中)

**Comment by h-east** [comment]
pushしました。( @crazymaster さんの指摘も修正済み)
https://github.com/vim-jp/vimdoc-ja/commit/417f995a760ec227bbed9ae5cac641e587a50d24

**Comment by h-east** [comment]
[wiki Vim ドキュメント翻訳者の手引き](https://github.com/vim-jp/vimdoc-ja/wiki/Guide)の「モードの名称」の部分も修正しました。

**Comment by h-east** [comment]
commitメッセージには書いたけどここに書くのを忘れてた。
すべての .jax の'Operator-pending' を "オペレータ待機" に統一して 関連部分も修正してます。

**Comment by h-east** [comment]
特にヤカられなかったので問題なしと判断します。閉じます。ありがとうございました。

**Comment by ynkdir** [comment]
:+1:
