### ISSUE TITLE
pi_logipat.txt を翻訳する

### ISSUE THREAD

**Issue by crazymaster** [vim-jp/vimdoc-ja#126]
新規追加されたので意識共有のために立てておきます。
[Add the logiPat plugin to the distribution. · vim/vim@e2db6c9](https://github.com/vim/vim/commit/e2db6c975b97685ca58bd767a2b98cd8a94c1938)

**Comment by tyru** [comment]
面白そうなプラグイン。
netrwの作者さん作ですね。

**Comment by crazymaster** [comment]
Fixed by #177
