### ISSUE TITLE
eval.jax更新中 (WIP)

### ISSUE THREAD

**Issue by h-east** [vim-jp/vimdoc-ja#127]
eval.jaxを最新に追従途中。3536行までは完了。3537～が未です。
https://gist.github.com/h-east/4d7f5c5c849d4138928d

私は今から月曜までは作業出来ないのでどなたか続きをやって貰えると嬉しいです。

**Comment by h-east** [comment]
続きやってます。

原文 eval.txt : L4892 (`readfile`の部分)
`When {binary/append} contains "b" binary mode is used: ` の `/append`は誤記ですよね？
`writefile()`の`flags`と混同してる感じ。

**Comment by h-east** [comment]
devel 更新しました。チェックお願いします。
https://github.com/vim-jp/vimdoc-ja/commit/93bd51c30cbe3c20996ebdb0429f5e397369ae7b

**Comment by ynkdir** [comment]
:+1: 

> 原文 eval.txt : L4892 (readfileの部分)

ですね

**Comment by h-east** [comment]
微調整。`virtcol()`の`v`の説明文を`col()`, `line()`と同じにしました。
https://github.com/vim-jp/vimdoc-ja/commit/2a453f336ddab5fd7cfee98533759d3568c150a3

@ynkdir Thanks. 
私、当分翻訳疲れしているので、どなたかvim_devに報告して頂けると嬉しいです。:cat2:

**Comment by h-east** [comment]
いちおうeval.jaxの更新やりきったのでIssue閉じます。

**Comment by ynkdir** [comment]
報告しました。

https://groups.google.com/d/msg/vim_dev/Hu52Qo3vHzs/YgFJKpTN1oQJ

**Comment by h-east** [comment]
@ynkdir 早っ！ありがとうございます。

**Comment by nakinor** [comment]
5621 行目の『{skipcc} を省略。またはゼロを指定すると、合成文字は別々にカウントされる。』の「省略」に続く句点「。」は無い方がいいかも......なんて思いました。

**Comment by h-east** [comment]
@nakinor Thanks. その通りです。self校正漏れでした。修正しました。masterには十数分で反映されます。
https://github.com/vim-jp/vimdoc-ja/commit/4d2108b79aa6f756649083e26893a79d915e10be

**Comment by k-takata** [comment]
> When {binary/append} contains "b" binary mode is used: の /appendは誤記ですよね？

原文に修正が反映されました。
https://github.com/vim-jp/vim/commit/64a00ae5e8b4413ed046485b54346c694d6520f8#diff-bea881dfa9626bab7141337b0fcdb23eL4898
