### ISSUE TITLE
'indentkeys' の記述について

### ISSUE THREAD

**Issue by machakann** [vim-jp/vimdoc-ja#128]
options.txt 4298行目付近

>     A list of keys that, when typed in Insert mode, cause reindenting of
>     the current line.  Only happens if 'indentexpr' isn't empty.
>     The format is identical to 'cinkeys', see indentkeys-format.
>     See C-indenting and indent-expression.

options.jax 4395行目付近

>   挿入モードで打ち込まれたときに、現在行の再インデントを引き起こすキーの
>   リスト。これはオプション 'indentexpr' が空でないときのみ起きる。
>   書式は 'cinkeys' によって異なってくる。indentkeys-format を参照。
>   C-indenting と indent-expression を参照。

「書式は 'cinkeys' と同様である。」が適切かと思います。

**Comment by crazymaster** [comment]
Thanks!
