### ISSUE TITLE
tabpagewinnr() 関数の記述について

### ISSUE THREAD

**Issue by machakann** [vim-jp/vimdoc-ja#130]
`tabpagewinnr()@en`
> tabpagewinnr({tabarg} [, {arg}])			*tabpagewinnr()*
> 		Like |winnr()| but for tab page {tabarg}.
> 		{tabarg} specifies the number of tab page to be used.
> 		{arg} is used like with |winnr()|:
> 		- When omitted the current window number is returned.  This is
> 		  the window which will be used when going to this tab page.
> 		- When "$" the number of windows is returned.
> 		- When "#" the previous window nr is returned.
> 		Useful examples:
> 		    tabpagewinnr(1)	    " current window of tab page 1
> 		    tabpagewinnr(4, '$')    " number of windows in tab page 4
> 		When {tabarg} is invalid zero is returned.

`tabpagewinnr()@ja`
> tabpagewinnr({tabarg} [, {arg}])			*tabpagewinnr()*
> 		|winnr()|と同様だが、タブページ{tabarg}を対象とする。
> 		{tabarg}は対象とするタブページの番号を指定する。
> 		{arg}は|winnr()|の場合と同じように扱われる。すなわち:
> 		- 省略するとカレントウィンドウの番号を返す。これは、このタブペー
> 		  ジに入るとき使われるウィンドウである。
> 		- "$" とするとウィンドウ番号を返す。
> 		- "#" とすると前のウィンドウ番号を返す。
> 		役に立つ例:
> 		    tabpagewinnr(1)	    " タブぺージ1のカレントウィンドウ
> 		    tabpagewinnr(4, '$')    " タブページ4内のウィンドウの個数
> 		{tabarg}が無効なときは0を返す。

日本語ヘルプ (eval.jax 5982行目辺り) の

>  		- "$" とするとウィンドウ番号を返す。

の部分ですが、機能を考えると「"$" とするとウィンドウの個数を返す。」とするのはどうでしょうか。「役に立つ例」ではそのようになっていますので統一の意味でもその方がよいかと思います。

**Comment by h-east** [comment]
@machakann :+1: 賛成です。

**Comment by crazymaster** [comment]
ありがとうございます。取り込みました。

**Comment by machakann** [comment]
ありがとうございます。

# あれ、私のコミットになっている？何か不思議なことが…

**Comment by crazymaster** [comment]
`git commit --author="User Name <foo@bar.com>"`
でAuthorを指定しました。

**Comment by crazymaster** [comment]
ちなみにCommitterは私になっています。

**Comment by machakann** [comment]
なるほど、そんな機能が。勉強になります。
