### ISSUE TITLE
https://sites.google.com/site/vimdocja/ について

### ISSUE THREAD

**Issue by crazymaster** [vim-jp/vimdoc-ja#132]
旧サイトが生きていてコンテンツが重複している状態になっており、SEOの観点上好ましくありません。
また、検索語句によっては旧サイトがヒットしてしまうため煩わしさを感じると思われます。

移転してからそろそろ4年は経つので旧サイトの方は閉鎖 or リダイレクトしても良いのではないでしょうか。

**Comment by ynkdir** [comment]
そうですね。
閉鎖 or リダイレクトはどちらでも構わないですがなんとなく閉鎖(サイト削除?)に一票。

**Comment by h-east** [comment]
@crazymaster :+1: お任せします。

**Comment by crazymaster** [comment]
@h-east 私は権限を持っていないので作業は他の方にお任せするようになります。

**Comment by ynkdir** [comment]
では、異論がなければ 30 日に閉鎖します。

**Comment by ynkdir** [comment]
削除しました。

> このサイトはすぐに削除されますが、30 日以内であれば、URL（sites.google.com/site/vimdocja）にアクセスすれば復元できます。

だそうです。

**Comment by crazymaster** [comment]
:+1:
