### ISSUE TITLE
Vim のソースとの齟齬: location list

### ISSUE THREAD

**Issue by hokorobi** [vim-jp/vimdoc-ja#134]
「location list」は Vim のソース（src/po/ja.poなど）では「場所リスト」となっていますが、ドキュメントでは「ロケーションリスト」となっていました。
可能なら統一したほうが良いかなと思いました。

**Comment by crazymaster** [comment]
どちらに倒すかが問題ですね...

**Comment by h-east** [comment]
ヘルプはすべて「ロケーションリスト」で統一されているので `src/ja.po` の方もそちらに合わせた方が良いと思います。
修正箇所2箇所ですし。
`src/ja.po`以外で`場所リスト`になっているところありましたっけ？

**Comment by crazymaster** [comment]
翻訳ファイルの方を直すのであれば vim-jp/lang-ja にpull-reqするようになるのかな。
今のところ更新が滞っていますが...

**Comment by h-east** [comment]
:+1:

**Comment by nakinor** [comment]
どこに書くべきか迷いましたがここに。

#44 の「リカバリ」の統一作業中に気がついて調べたのですが、ja.po を尊重して下記の通りに jax を修正していった方が良いでしょうか？

1. より、recovery は「リカバリ」にします。
2. より、どないしょ〜。できれば ja.po の方を修正して欲しい。
3. より、それぞれ「オペレータ」「キャラクタ」「フィルタ」「ポインタ」「メンバ」にします。
4. より、予定通りにします。

## メモ
### 1. ja.po の中で統一されていないもの
- アプリケーション 1、アプリ 1
L2211 msgstr "E672: MDIアプリの中ではウィンドウを開けません"

- バッファ 72、バッファリスト 1、バッファー 1
ちなみに jax では「バッファ」に統一してある

- リカバリ 4、リカバー 1
ちなみに jax ではまだ作業をしていない「リカバリー」にする予定だった

### 2. すでに統一された jax と差異が生じているもの
- カンマ 4
jax では「コンマ」に統一してある(あ！options.jax に 1 つ残ってる……)

- サーバ 15
jax では「サーバー」に統一してある

- ユーザ 16
jax では「ユーザー」に統一してある(あ！vim_faq.jax に 8 つも残ってる……)

### 3. jax ではまだ作業していないもの(予定と違ったもの)
- オペレータ 3
jax ではまだ作業をしていない「オペレーター」にする予定だった

- キャラクタ・デバイス 1
jax ではまだ作業をしていない「キャラクター」にする予定だった。あと中黒は？

- フィルタ 4
jax ではまだ作業をしていない「フィルター」にする予定だった

- ポインタ 1、ポインタブロック 4
jax ではまだ作業をしていない「ポインター」にする予定だった

- メンバ 1
jax ではまだ作業をしていない「メンバー」にする予定だった

### 4. jax ではまだ作業していないもの(予定と同じだったもの)
- クエリー 2
jax ではまだ作業をしていない「クエリー」にする予定だった

- コンパイラ 2
jax ではまだ作業をしていない「コンパイラ」にする予定だった

- コンピュータ 2
jax ではまだ作業をしていない「コンピュータ」にする予定だった

- ディレクトリ 20
jax ではまだ作業をしていない「ディレクトリ」にする予定だった

- プロパティ 1
jax ではまだ作業をしていない「プロパティ」にする予定だった

- メモリ 8
jax ではまだ作業をしていない「メモリ」にする予定だった

**Comment by koron** [comment]
ja.poは、稀に幅を意識しなきゃいけないので、両方まとめて統一というのは、優先度下げたほうが良いです。

**Comment by koron** [comment]
あと閉じてしまったor実質終わっているissueに書くより、新たに書き起こしてもらったほうが、助かります。

**Comment by nakinor** [comment]
ありがとうございます。そしてすみませんでした。

> 幅を意識しなきゃいけない

とのことなので「意識して長音符を省略している可能性がある」のですね。

#44 でこれから寄せていくものは ja.po を尊重して修正していきます。先のコメント 2. については多いので最後に作業することにします。

**Comment by crazymaster** [comment]
> サーバ 15
> jax では「サーバー」に統一してある
> 
> ユーザ 16
> jax では「ユーザー」に統一してある(あ！vim_faq.jax に 8 つも残ってる……)

これらに関しては長音を付ける方向に作業済み or マージ予定です

**Comment by hokorobi** [comment]
修正ありがとうございます。

**Comment by crazymaster** [comment]
> 幅を意識しなきゃいけない
> とのことなので「意識して長音符を省略している可能性がある」のですね。

むしろこれはインデント、センタリング制御を気にする必要のあるものが存在し、
単に置換すればよいわけではないので、優先度を下げましょうということだと思います。

**Comment by crazymaster** [comment]
ja.po の方だけを尊重する必要はなくて、jaxとja.poを合わせて検討すべきだと思います。

**Comment by nakinor** [comment]
リカバリ、オペレータ、キャラクタ、フィルタ、ポインタ、メンバの作業は後回しにして、カンマへの変換も最後にします。
