### ISSUE TITLE
Typo in sign.jax

### ISSUE THREAD

**Issue by lesguillemets** [vim-jp/vimdoc-ja#135]
[sign.jax#L19](https://github.com/vim-jp/vimdoc-ja/blob/master/doc/sign.jax#L19)

> デバッガやその他のIDE{訳注: 統合開発環境}ツールはエディタをコントールする。

s/コントール/コントロール，だと思います．

**Comment by crazymaster** [comment]
Thanks!

**Comment by lesguillemets** [comment]
早速ありがとうございました！
