### ISSUE TITLE
マネージャー or マネージャ -> マネージャに統一したい

### ISSUE THREAD

**Issue by nakinor** [vim-jp/vimdoc-ja#140]
「マネージャ」に統一したい。

例の告示によると er と付くものは原則「ー」を付けることになっているのだが……。これどないしょ。

```
ジャ    453
ジャー  7
```

「ジャ」に寄せるなら下記 2 ファイルを修正

```
os_mint「ウィンドウマネージャーと仮想コントロール」
os_w16 「(ファイルマネー)ジャーの "関連付け" 機能を使用する」
他5    「メジャー」もしくは「ジャーナル」
```

「ジャー」に寄せる場合だと整形つらくない？自動で出来るんだっけか。「ジャ」なら修正するファイルは 2 つだけ。手動でできる。

**Comment by koron** [comment]
マネージャー、でしょう。根拠は例の内閣告示第二号。

**Comment by nakinor** [comment]
ありがとうございます。「マネージャー」でいきます。

**Comment by nakinor** [comment]
ジャンプ、プロシージャが多く引っかかるだけで、実際に修正が必要なのは下記の 15 ファイルのようです。

```
ft_ada   1
gui_x11  7
options  1
starting 1
syntax   1
term     1
usr_09   1
usr_31   1
usr_90   1
```

**Comment by nakinor** [comment]
2fb6624 で
