### ISSUE TITLE
アイデア or アイディア -> アイディアに統一したい

### ISSUE THREAD

**Issue by nakinor** [vim-jp/vimdoc-ja#141]
「アイディア」に統一したい。

特に根拠とできるものはなく「アイデア」の方が良く使われている印象。自分も「アイデア」育ち。発音によるなら「アイディア」の方が良さそうだし、ネイティブの発音を手軽に聞ける現在となっては、若者は「アイデア」だと違和感を感じるのではないかな？

```
アイディア  9
アイデア    6
ディア     27
デア        7
```

「ディア」の中で関係ないものは下記の 18 個所。(- 27 18) -> 9 なので、「アイディア」は改行で分割されていないはず。

```
mbyte    エンディアンx8
options  エンディアンx1
         メディアx2
starting メディアx2
usr_21   メディア
usr_45   エンディアン
vim_faq  エンディアンx3
```

「アイデア」と「デア」の違い 1 つは fold の個所みたい。

```
fold    (アイ)デアではない
fold 1 つ分割されている。
```

マニュアル内での割合は アイディア：アイデア = 9:7 となっている。

「アイディア」に寄せるなら下記を修正する。

```
eval    1 か所
syntax  1 か所
usr_41  3 か所
visual  1 か所
fold    1 か所(改行されてるよ！)
```

「アイデア」に寄せるなら下記。

```
if_tcl    1 か所
intro     4 か所
motion    1 か所
quickfix  1 か所
tips      2 か所
```

**Comment by koron** [comment]
アイデア、細則4の注2、かな。

**Comment by nakinor** [comment]
ありがとうございます。「アイデア」でいきます。

**Comment by nakinor** [comment]
0e8d276 で
