### ISSUE TITLE
multi-lingual の意味について

### ISSUE THREAD

**Issue by nakinor** [vim-jp/vimdoc-ja#153]
たぶん「多国語」のタイポだと思うのですが、もしかしたら C だけでなく C++ や Java 等にも使える「多言語」という意味で使われているのでしょうか？(でもそれなら multi-language を使っている？)

- if_cscope.jax L454
> また cscope 13.x や mlcscope 14.x (他国後バージョンのcscopeで、C, C++, Java, lex, yacc, breakpoint listing, Ingres, and SDL をサポートしている) を次のサイトからダウンロードできる。

- if_cscope.txt L471
> Also you can download cscope 13.x and mlcscope 14.x (multi-lingual cscope which supports C, C++, Java, lex, yacc, breakpoint listing, Ingres, and SDL) from World-Wide Exptools Open Source packages page:

**Comment by h-east** [comment]
@nakinor 明らかに「多国語」のtypo(というか漢字変換ミス)だと思います。修正しちゃって下さい。

**Comment by nakinor** [comment]
「多国語」で修正しました。

**Comment by k-takata** [comment]
> もしかしたら C だけでなく C++ や Java 等にも使える「多言語」

こっちの意味で使われている気がします。

**Comment by h-east** [comment]
すいません。その通りです。修正しました。(`他国後`というtypoに引きずられてしまいました)
https://github.com/vim-jp/vimdoc-ja/commit/19ff0b5266e92927776e6959317de2d92baad0c4
