### ISSUE TITLE
options.jax の shellxquote の項について

### ISSUE THREAD

**Issue by nakinor** [vim-jp/vimdoc-ja#155]
すみません。options.jax の shellxquote の項について 2 つ質問があります。赤ペン先生、お願いします。

1. 「サードパーティ」の表記統一をしていたのですが、下記の段落において、原文には 3rd-party が 1 つしか出ていないのに対して、訳文ではサードパーティが 2 つ出てきています。どのような解釈によるものなのでしょうか？
「cmd.exe」と「MKS Korn Shell や bash」を修飾する部分が長いので、とりあえず先に「どっちを使っても便利である」ことを言ってしまい、あとでそれぞれについて説明したということでしょうか？

2. 日本語訳を読んでもすんなりと頭に入ってこなかったのですが、つまり「Win32 版では cmd.exe を使うか (MKS...や) bash を使うかで設定を変える必要があるのだけど、Vim は賢いから 'shell' を見て適切に値を決めるため、ユーザーはあまり気にしなくていいよ」ということでしょうか？

- options.jax L6431

> ほとんどのシステムでは初期設定は空になる。このオプションは Win32 版で
> cmd.exe やサードパーティーのシェルを使う場合に便利である。cmd.exe は自
> 動的にコマンドの最初と最後のクォート文字を取り除く。MKS Korn Shell や
> bash などのサードパーティー製のシェルを使う場合は設定値は "\"" とすべ
> きである。ユーザーがこのオプションを設定する必要がないように、初期設定
> は 'shell' に適した値が設定される。|dos-shell| を参照。

- options.txt L6309

> This is an empty string by default on most systems, but is known to be
> useful for on Win32 version, either for cmd.exe which automatically
> strips off the first and last quote on a command, or 3rd-party shells
> such as the MKS Korn Shell or bash, where it should be "\"".  The
> default is adjusted according the value of 'shell', to reduce the need
> to set this option by the user.  See |dos-shell|.

```
これは空文字だよ、デフォルトでは、ほとんどのシステム上においてね、
だけどこれ(This の省略？)は Win32 版では便利であることが知られているよ、
(either 〜 or 〜 のここ、何か関係詞が省略されてる？cmd.exe には for が付いているけど、shells には for が付いていないから解釈が違う？)
何の Win32 版かというと、次のどっちかだよ(二者択一というよりはどっちでもみたいな感じ？)、
自動的にコマンドの最初と最後のクォートを取り除く(挙動をする) cmd.exe か、
値を "\"" とすべき MKS Korn Shell や bash のようなサードパーティ製シェルかだよ。
デフォルトは shell の値によって調整されるよ(according に to 要らないの？)、
減らすために(何の？)ユーザーによるオプションをセットする必要をさ。
```

**Comment by ynkdir** [comment]
たしかに読みにくいですね。
解釈はそれであってると思います。

**Comment by nakinor** [comment]
ありがとうございます。
現状の訳文のまま、表記を統一するだけにしました。
