### ISSUE TITLE
日本語manファイルをlang-jaに移管

### ISSUE THREAD

**Issue by k-takata** [vim-jp/vimdoc-ja#156]
https://github.com/vim-jp/lang-ja/issues/22 の件、こちらにも立てておきます。

vimdoc-ja には、以下の日本語manファイルが含まれていますが、本家に取り込まれているファイルを一括管理するという意味で lang-ja に移管したほうがよいと思います。

* evim-ja.UTF-8.1
* vim-ja.UTF-8.1
* vimdiff-ja.UTF-8.1
* vimtutor-ja.UTF-8.1
* xxd-ja.UTF-8.1

いかがでしょうか。

**Comment by koron** [comment]
vim-jp/lang-ja#22 って書くと、双方向リンクになるはず。

**Comment by ynkdir** [comment]
ok です

2016年1月26日(火) 10:21 MURAOKA Taro <notifications@github.com>:

> vim-jp/lang-ja#22 <https://github.com/vim-jp/lang-ja/issues/22>
> って書くと、双方向リンクになるはず。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vim-jp/vimdoc-ja/issues/156#issuecomment-174757209>.
>
-- 
Yukihiro Nakadaira - yukihiro.nakadaira@gmail.com

**Comment by mattn** [comment]
こちらにも。

okです。

**Comment by crazymaster** [comment]
https://github.com/vim-jp/vimdoc-ja/pull/161 移管されたので閉じます
