### ISSUE TITLE
翻訳管理ツールの導入

### ISSUE THREAD

**Issue by mattn** [vim-jp/vimdoc-ja#157]
これを使うという話ではないです。
もし有益だったらこういうのもアリじゃない？ってレベルの話です。

![](https://gyazo.com/b1e6e3e37fff0e1bf61a1107ffc5241c.png)

そこそこ使いやすい気もしますし、使いにくい気もします。

https://www.transifex.com/vim-jp/vimdoc-ja/

お時間あればお試しあれ。
現在はサンプルのテキストファイルのみ用意しています。

**Comment by koron** [comment]
jax のような、変にフォーマットを持ったものには使いづらいのでは?

transifex は po とかメッセージの話で、やるなら lang-ja ですかね。
ただVimはプロセスが微妙にアレだし、既に殆ど翻訳済みなので、
手間が増えるだけで美味しくないかも。
Vim全体がtrasifexで管理します、なら乗りたいけれど
変える意味があるかは…わがんね

**Comment by mattn** [comment]
git 知らない人でも参入できる何かがあればいいなーと思いました。

**Comment by crazymaster** [comment]
po4a (PO for anything) が使えそう？

**Comment by koron** [comment]
リンクとか書いてくれると嬉しかったかも。

https://po4a.alioth.debian.org/index.php.ja

**Comment by koron** [comment]
タイトルを、抽象化・一般化したものに変更しました。

**Comment by Milly** [comment]
> git 知らない人でも参入できる何かがあればいいなーと思いました。

(git 知らなくても) github.com にユーザー登録できる程度の人なら参入できるかもしれないやつがマージされました。
* Add edit link toward github #242

**Comment by mattn** [comment]
GitHub 編集リンクも入り少しは状況が変わるかもしれないですね。この issue に関しては実際の問題と解決へのアプローチが見えてないのでいったん close します。
