### ISSUE TITLE
表記揺れ統一:「気を付けて」or「気をつけて」?

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-ja#158]
vim-jp/lang-ja#24 で気になったので #44 に関連して。

* 「気を付けて」
* 「気をつけて」

の表記が混在しています。
どちらかに統一したほうが良いでしょう。

**Comment by koron** [comment]
なんとなく twitter の vote 作ってみたw
https://twitter.com/kaoriya/status/692454281824358400

**Comment by crazymaster** [comment]
Google 検索
気をつけて - 約 29,200,000 件
気を付けて - 約 16,200,000 件

**Comment by koron** [comment]
投票的には「気をつけて」が大差で優勢ですね。

lang-ja のほうでも統一を検討中。

**Comment by nakinor** [comment]
ja.po では「気を付け」は「気をつけ」に統一されたようですが、jax では「気付」と「気づ」のブレもあります。「気が付」は現状漢字のみです。すべてひらがなに開くのはどうでしょうか？あとあまり関係ありませんが「気に喰わない」も「気に入らない」にすれば良いと思いました。

指示を頂けたら作業します！

### 気をつけに統一するもの
#### 気を付け
！eval.jax: L6227 自分自身で気 &lt;CR&gt; を付けなければならない。
gui.jax: るかもしれない。だから気を付けて!
gui_x11.jax: しれない。だから気を付けなくてはならない!
options.jax: 気を付けてほしいのは、expression はステータス行が表示されるたびに
options.jax: ステータス行で expression を使うときはエラーに気を付けること。
print.jax: ジ文字を使って原始的な印刷制御ができますが、いくつか気を付けること
repeat.jax: うに気を付けること。
sign.jax: 気を付けなければならない
syntax.jax: たディレクトリに構文ファイルを置くように気を付ければ良い。
usr_09.jax: カレントセレクションと真のクリップボードは気を付けて使いさえすれば

### 気付 or 気づ
#### 気付(か行)(指示があれがGo!)
editing.jax: 元のファイルが必要なことに気付いたときは、
editing.jax: ことが起きていることを気付かせるために、
editing.jax: ファイルのタイムスタンプが変更されたことにVimが気付いたとき、
recover.jax: その人はあなたのスワップファイルに気付かないし、
repeat.jax: を抜けるまでその作用に気付き難いからである。
tagsrch.jax: 誰かが気付かれないように実行される厄介なコマンド
undo.jax: 以前の状態を復元することに気付くでしょう。
usr_05.jax:Tab 行末には $ と表示され、通常なら気付かないよう
usr_10.jax: ミスがあることに気付きました。
usr_10.jax:	見た目では気付きにくいので注意！
！usr_44: L447 構文グループを作成するということに気 &lt;CR&gt; 付くと思います。

#### 気づ(か行)(変えない)
ft_sql.jax: キャッシュされているため時間がかからないことに気づくでしょう。
if_sniff.jax: ファイルがセーブされると SNiFF+ はそれに気づいて、
insert.jax: まず最初にたくさんの異なる構文グループがあることに気づくだろう。
os_win32.jax: バーでウィンドウタイトルが点滅するのに気づくだろう。
spell.jax: 上のようにまた遅延に気づくかもしれない。
term.jax: それに気づいて自動的に 8 ビットの設定を使うようになります。
usr_02.jax: 元の方が良かったと気づくことがあると思います。
usr_02.jax: ヘルプを読むと、縦棒 "|" で囲まれた文字に気づくと思います
usr_05.jax: が達する前にスクロールが始まることに気づくと思います
usr_06.jax: 白黒のテキストがあなたの足を引っ張っていたことに気づくでしょう。
usr_20.jax: "col" が "cow" の入力ミスであることに気づきました。
！usr_20.jax: L271 "is" で始まっていないことに気づ &lt;CR&gt; いたと思います。
usr_27.jax: それでも気づかないことがあるかもしれません。
usr_41.jax: 'modifiable' is off" のような有効なエラーに気づくことができません。
version4.jax: 普通はこの変更による違いは気づかないかもしれません。
version4.jax: アンドゥしてよいか気づくのが困難でした。

### 「付」をひらがなに開くならこれも？
#### 気が付 (「気がつ」は無い)(指示があれがGo!)
gui_w32.jax: ファイルタイプの関連付けを抑制してしまうことに気が付いたら、
usr_27.jax: これに気が付かないと永遠に検索を続けることになってしまいます!

### 気に入らない or 気に喰わない
#### 気に喰わない(指示があれがGo!)
pi_spec.jax: 気に喰わないならば、独自のキーを設定するのも良いだろう。

#### 気に入らない(変えない)
fold.jax: それが気に入らないのならば、
gui.jax: 標準のメニューが気に入らなければ、
options.jax: 'cindent' の動作が気に入らないならば、
os_beos.jax: これが気に入らなければ環境変数VIM
pi_spec.jax: リリース更新機能が気に入らず、
syntax.jax: 標準の構文ファイルが気に入らない場合や、

**Comment by koron** [comment]
賛成です :+1: :cake:

**Comment by nakinor** [comment]
作業完了しましたけど、クローズできませんか？

**Comment by koron** [comment]
@nakinor クローズしてくれても、良いのよ?w
