### ISSUE TITLE
ブランチ名を develop に変更したい

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-ja#160]
なんか自分でやっておいてなんだけど devel ってあんまりだと思えてきた。
(たぶん古い慣習を引きずった)

今のままの方が良い、って人が多いならやりませんので、意見を聞かせてください。

**Comment by thinca** [comment]
:+1:

**Comment by thinca** [comment]
もしくは、git-flowなどで使われている `master`/`develop` と本リポジトリは運用方法が違うので、混乱を避けるために全く別の名前にしてもいいかもしれないですね。`working` とか。

**Comment by koron** [comment]
ですね。

最終的には、現行のdevelを別レポジトリ分離しちゃうのもありかしら?

**Comment by koron** [comment]
#223 作ったので、こっちは閉じます。
