### ISSUE TITLE
tutor.jaをlang-jaに移管

### ISSUE THREAD

**Issue by k-takata** [vim-jp/vimdoc-ja#181]
#156 に関連して、tutor.ja も lang-ja に移管したほうがよいのではと思ったのですが、どうでしょうか。

\# というか、存在を忘れていましたｗ

**Comment by koron** [comment]
@mattn どうです?

**Comment by mattn** [comment]
いいと思いますよ。僕、住み分けがよく分かってないですが。

**Comment by k-takata** [comment]
> 住み分けがよく分かってないですが。

vim本体のソースに含まれている日本語翻訳ファイルは全部 lang-ja でまとめて管理した方が分かりやすいのではないかという意図で提案しています。

**Comment by mattn** [comment]
>vim本体のソースに含まれている日本語翻訳ファイルは全部 lang-ja でまとめて管理した方が分かりやすいのではないかという意図で提案しています。

なるほど。

**Comment by k-takata** [comment]
特に反対意見もないようですので、向こうに PR を立てました。

**Comment by koron** [comment]
そしてマージしました。

**Comment by k-takata** [comment]
では、こちらから消さないと。

**Comment by koron** [comment]
では消すまで開いておきましょ

**Comment by k-takata** [comment]
削除しました。
\# masterブランチじゃないから自動クローズされないのか…。
