### ISSUE TITLE
channel 関係のキャッチアップ

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-ja#191]
チャンネル関係の関数名が変更になりました。
eval.txtに加えてchannel.txtも更新が予想されます。
これらをキャッチアップしましょう。

**Comment by tyru** [comment]
(channel.txt なんて増えたのか…)

**Comment by koron** [comment]
初版は僕が爆速で翻訳しました!

**Comment by k-takata** [comment]
なぜ 7.4.1244 で、channel.txt が一緒に更新されなかったのか…

**Comment by rbtnn** [comment]
> Inter-process communication:
>	connect()		open a channel
>	disconnect()		close a channel
>	sendexpr()		send a JSON message over a channel
>	sendraw()		send a raw message over a channel
>	jsonencode()		encode an expression to a JSON string
>	jsondecode()		decode a JSON string to Vim types

usr_41.txtも更新されてないので、ちょっと修正が必要になりそうですね。

**Comment by k-takata** [comment]
Runtimeファイルの更新でchannel.txt, usr_41.txtが更新されました。

**Comment by crazymaster** [comment]
差分を日本語版に反映し終わったので、こちらは閉じます。
翻訳についてはvimdoc-ja-workingの別issueで
