### ISSUE TITLE
webの左枠 に channel を追加する

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-ja#198]
特定機能あたり、かな?

![01](https://cloud.githubusercontent.com/assets/468368/12818154/f9c50da6-cb98-11e5-963c-f97b73fc03ce.png)

**Comment by koron** [comment]
もしかしたら本家のドキュメント修正案件?

よく覚えてない。

**Comment by k-takata** [comment]
help.jax から生成？

**Comment by koron** [comment]
そうっぽいかも。

**Comment by crazymaster** [comment]
左枠の部分はテンプレートを修正ですね
参考: https://github.com/vim-jp/vimdoc-ja/commit/46ad9b788d114c851406d76ca1ec7ad3c42af0b7

help.txtにリンクがないのについては本家のドキュメント修正案件ですね

**Comment by koron** [comment]
:bow:
