### ISSUE TITLE
表記ゆれ、dict.ymlの修正、もしくはnvcheckのデバッグ

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-ja#208]
```
$ nvcheck.exe doc/*.jax
doc/autocmd.jax:890: オペレーター >> オペレータ
doc/insert.jax:1805: ビジュアル置換モード >> 仮想置換モード
doc/map.jax:22: オペレーター >> オペレータ
doc/map.jax:790: オペレーター >> オペレータ
doc/map.jax:792: オペレーター >> オペレータ
doc/map.jax:792: オペレーター >> オペレータ
doc/map.jax:793: オペレーター >> オペレータ
doc/pattern.jax:188: 演算コマンド >> オペレータ
doc/pattern.jax:210: 演算コマンド >> オペレータ
doc/pi_netrw.jax:1894: サーバ >> サーバー
doc/syntax.jax:3237: アスキー >> ASCII
doc/visual.jax:97: ビジュアル矩形 >> 矩形ビジュアル
doc/visual.jax:98: ビジュアル矩形 >> 矩形ビジュアル
doc/visual.jax:100: ビジュアル矩形 >> 矩形ビジュアル
```

**Comment by koron** [comment]
`コアスキーマ` が `アスキー｀ として検出されてもうたwww

**Comment by koron** [comment]
doc/pi_netrw.jax:1894: サーバ >> サーバー

書名の一部なので検出したくない。

**Comment by koron** [comment]
doc/visual.jax:97: ビジュアル矩形 >> 矩形ビジュアル
    doc/visual.jax:98: ビジュアル矩形 >> 矩形ビジュアル
    doc/visual.jax:100: ビジュアル矩形 >> 矩形ビジュアル

以下の様な、空白を含む部分の誤検出

    ビジュアル	   矩形ビジュアル

nvcheck のアルゴリズム修正が必要そう

**Comment by koron** [comment]
def40c24a307bdbd43c288681abcaee7f42d914f の細工で、以下については誤検出を回避できました。

    doc/pi_netrw.jax:1894: サーバ >> サーバー
    doc/syntax.jax:3237: アスキー >> ASCII

**Comment by tyru** [comment]
> `コアスキーマ` が `アスキー` として検出されてもうたwww

![週刊アスキー](http://weekly.ascii.jp/elem/000/000/123/123564/2013_1_15_914_cover_480_o_.jpg)

**Comment by nakinor** [comment]
「何」は「んなに」でどうでしょう？
こんなに、そんなに、あんなに、どんなに、みんなに等、
「何」にならないものは「ん＋なに」になっているようですが。

**Comment by koron** [comment]
https://github.com/koron/nvcheck/commit/cdd703eb4e5bba83146b831cff20833b919bcc69 で doc/visual.jax の空白の扱いを正したのだが…

98行目から99行目にかけてのこれで…

```
ビジュアル	    ノーマル	   矩形ビジュアル	  行ビジュアル
矩形ビジュアル	    ビジュアル	   ノーマル		  行ビジュアル
```

`ビジュアル\n矩形(ビジュアル)`

うわあああああああああああああああ! (´・ω・`)

**Comment by koron** [comment]
@nakinor それならば `何` を登録した上で def40c24a307bdbd43c288681abcaee7f42d914f でやったように
許容するパターン `こんなに`, `あんなに` などなどを、追加しちゃうのが良いかもですね。

**Comment by nakinor** [comment]
「ビジュアル(空白改行)矩形」の誤検出 3 つは、
幸いにして「ビジュアル矩形ビ」の形になっているので、今回はこれを登録して逃げるとか。
vim_faq の 5 つは完全なる「ビジュアル矩形」なので修正します。

**Comment by koron** [comment]
`なに` はうまくいかなかった。たぶんnvcheckの問題。

**Comment by koron** [comment]
@nakinor nvcheck のほうで「単語に空白を含められるようになった」ので
`pixmap ～` がもう対応できます。最新版を試してみてください。

**Comment by nakinor** [comment]
確認しました！
いやこれ、めっちゃイイですね。
速度ぜんぜん落ちない！

**Comment by koron** [comment]
> 速度ぜんぜん落ちない！

ええ。そのような方式(1passで済む方式)を採用していますのでw
1つ懸念されるのは、いまメモリのことあまり考えてないので
今後めちゃくちゃ辞書が大きくなった時、
メモリ馬鹿食いになったり起動までに時間がかかったりする可能性があります。
まぁ、そうなったとき考えるってことでお願いします。

**Comment by koron** [comment]
ということでこのissueは目的を果たしたということで、一旦は閉じます。
