### ISSUE TITLE
開発用のレポジトリと、公開用のレポジトリを分けたい

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-ja#223]
#160 の拡張を考えていたら欲が出てきました。

いっそのこと開発用のレポジトリと、公開用のレポジトリを分けたいです。
以下その **要件** です。

*   vimdoc-ja は公開用のレポジトリとし master & gh-pages だけにする
*   開発用のレポジトリは vimdoc-ja-working とし master & develop ほか、必要なブランチを作っていく
*   vimdoc-ja-working の master の内容は commit を契機に CI (できればCloud CI) でビルドし、  
    vimdoc-ja の master と gh-pages へ自動的に反映させる。

以下はその **計画案** です。

1. 新たに vimdoc-ja-tmp を作成する。これは現行の vimdoc-ja の master & gh-pages ブランチを push することで作る
2. vimdoc-ja に working ブランチを devel から作成。このブランチでは、CIでビルドして vimdoc-ja-tmp の両ブランチにcommitする各種スクリプト、を開発する
3. 2の開発の間、develへの変更は随時 working へマージする
4. (開発完了したら) vimdoc-ja-working レポジトリを作成する。 vimdoc-ja の working ブランチを devel をキャッチアップした後に、 vimdoc-ja-working の master ブランチとして push する。これ以降、vimdoc-ja の devel での作業は禁止とする
5. vimdco-ja-working のビルド用 CI を稼働させる
6. vimdoc-ja-working の更新先を vimdoc-ja-tmp から vimdoc-ja へ切り替える
7. 後始末する
    *    vimdoc-ja の master & gh-pages 以外のブランチを削除する
    *    vimdoc-ja で動かしているハズのビルド用のCIは止める
    *    vimdoc-ja-tmp を削除する

最後に分ける **動機** を上げておきます。

*   最新の翻訳を使いたいだけの人には、develの内容がgitで出てくるのは邪魔
    *   gh-pages も邪魔だが、これはいたしかたない…
*   翻訳作業をしている人にとっては、master & gh-pages が邪魔
    *    間違ったPRが出された時の破滅的なdiff。事故も怖い
    *   PR作るときに、始めに master との差分を計算するので、遅い

ご意見、よろしくお願いします。

----

参考資料:

*   travis-ci の基本
    *   [Environment Variables](https://docs.travis-ci.com/user/environment-variables/)
    *   [Customizing the Build](https://docs.travis-ci.com/user/customizing-the-build/)
*   travis-ci から push するほうほう
    *   [Auto-deploying built products to gh-pages with Travis](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd)
    *   [Travis-CI でコミットして GitHub にプッシュする - 公開鍵認証を利用してみる](http://blog.eiel.info/blog/2014/02/18/github-push-from-travis/) **採用予定**
    *   [Middleman で作った web サイトを Travis + GitHub pages でお手軽に運用する](http://tricknotes.hateblo.jp/entry/2013/06/17/020229)
    *   [Travis CIからgithub.ioにデプロイする方法](http://qiita.com/dora56/items/cafae475daec802b6b8f)

**Comment by tyru** [comment]
:+1: 

> 翻訳作業をしている人にとっては、master & gh-pages が邪魔

確かにほぼ履歴が被ってないので、 `git fetch` にやたら時間かかった覚えがあります。

**Comment by koron** [comment]
issue を vimdoc-ja-working として残す必要があるだろうか?
あるならば現行の vimdoc-ja を working に変更する計画を別途立案します。

**Comment by mattn** [comment]
今の vimdoc-ja を vim plugin にして使ってる人いるので、working に移動しても github がリダイレクトしちゃうんですよねー。issues だけ transfer 出来ればいいのだけど。

https://github.com/google/github-issue-mover

こういうのあるけど、引用タイプなのよね。

**Comment by koron** [comment]
んじゃissueは捨てる方向で、良さそうですね。

**Comment by koron** [comment]
とりあえず以下、3点は実施しました。

https://github.com/vim-jp/vimdoc-ja-tmp を作成 (ステップ1 完了)
working ブランチを作成した (ステップ2 完了)
とりあえず予約としてhttps://github.com/vim-jp/vimdoc-ja-working は作っておいた (ステップ4)

**Comment by koron** [comment]
参考資料: [Auto-deploying built products to gh-pages with Travis](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd)

**Comment by koron** [comment]
travisでhtmlをビルドするとして、それに使う vim はどうしよう?
sudo trueでapt-get installするのも、ソース持ってきてビルドするのも、バカらしい :sweat_smile:

**Comment by k-takata** [comment]
> travisでhtmlをビルドするとして、それに使う vim はどうしよう?

もともと入っているので十分なのでは？

**Comment by koron** [comment]
travis から push するには、2つ方法があるらしい。tokenを使う方法と、公開鍵を使う方法。

tokenはユーザが生成し、レポジトリを限定はできなさそう。
travis上では暗号化されているとはいえメンバーには丸見えなので、
なんでもできちゃってよろしくない。

公開鍵は、鍵ペアを作って公開鍵をgithubのvimdoc-ja(-tmp)に、
秘密鍵を暗号化してtravisに、それぞれ設定する。
これなら何かあっても被害はvimdoc-ja(-tmp)に限定される。

なので以下を参考にし、公開鍵方式を採用する方針。
[Travis-CI でコミットして GitHub にプッシュする - 公開鍵認証を利用してみる](http://blog.eiel.info/blog/2014/02/18/github-push-from-travis/)

**Comment by koron** [comment]
@k-takata 
> もともと入っているので十分なのでは？

まじで? ちょっとやってみるか…

**Comment by tyru** [comment]
> travisでhtmlをビルドするとして、それに使う vim はどうしよう?

vital.vim は Vim を取ってきてビルドしてますが、
vimdoc-ja は help なので元々入っているもので十分なんじゃないでしょうか。

**Comment by koron** [comment]
https://github.com/vim-jp/vimdoc-ja-tmp/commit/35dc7fa82362751f31f81f0f932afe886524cf9a

やっと travis-ci から commit & push でけた。

**Comment by koron** [comment]
https://github.com/vim-jp/vimdoc-ja-tmp/commit/64ca259befdb0050361f2c3de1dd2111816ecb29

master もイケた…これでほぼ開発工程はおしまい。

**Comment by koron** [comment]
200419e までで開発(ステップ2&3)が完了しました。

**Comment by koron** [comment]
あとは、レポジトリ絡みの操作を残すのみです。

**Comment by koron** [comment]
とりあえず、続きは #228 ということで、コチラは閉じます。
