### ISSUE TITLE
レポジトリ分割の最終作業

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-ja#228]
from #223 

レポジトリ分割のために必要な開発とテストは終わりました。
あとは実際に分割し、切り替えるだけの作業となります。
ただこれがちょっと複雑なので、以下に手順を書き下しておきます。

* [x] vimdoc-ja の devel での作業禁止を宣言する
* [x] working を devel にキャッチアップし vimdoc-ja-working の master として push (これを執筆時点の最新は、既にキャッチアップしてpushしてある)
* [x] vimdoc-ja の travis-ci を止める
* [x] 更新用cronを止める on @koron の自宅鯖
* [x] vimdoc-ja から master と gh-pages 以外のブランチを削除する
* [x] vimdoc-ja-tmp から Deploy Key を削除する (もしかしたらレポジトリ自体を先に消すかもしれない)
* [x] vimdoc-ja に Deploy Key (pub) を登録する
* [x] vimdoc-ja-working 用に travis-ci を設定する
* [x] vimdoc-ja-working の .travis.yml の `CI_KEY` (secure), `DEPLOY_BRANCH`, `DEPLOY_REPO_SLUG` を更新する (場合によってはDeploy Keyも作りなおす。その場合は2つ前の登録をやりなおし)

        travis encrypt -r vim-jp/vimdoc-ja-working "CI_KEY={PSK}"
* [x] vimdoc-ja-working の CI の正常動作を確認
* [x] vimdoc-ja-working のバッチURLを更新 (vimdoc-jaのバッチはTravis-CIが勝手に書き換えてくれる)
* [x] vimdoc-ja-tmp を削除する

以上

**Comment by koron** [comment]
最終勧告です。分割に反対の場合は、こっちで意見表明をおねがいします。
なぜ分割するのかについては #223 の記述を参照してください。

反応が薄ければ 2016/02/14 の23時ごろ(JST)をめどに、分割の最終作業を開始します。

**Comment by thinca** [comment]
:+1:

**Comment by tyru** [comment]
:+1:

**Comment by ynkdir** [comment]
:+1:

**Comment by nakinor** [comment]
vimdoc-ja-working を新規に clone して作業するようになりますか？
現状の remote の名前を変更すればいいのかな？
(高度過ぎてさっぱりわからんw)

**Comment by koron** [comment]
@nakinor remoteのURLを変えてブランチの関係を張り替えれば良いのですが、まぁgitに詳しくないならcloneし直すのが楽だと思います。

**Comment by koron** [comment]
現在艦これをしながら、手順を復讐しつつ待機中。

**Comment by koron** [comment]
いまから、作業を開始します。以後のdevelの更新は破棄されます。

**Comment by koron** [comment]
全作業、完了しました (｀･ω･´)ゞ

**Comment by thinca** [comment]
おつかれさまです！

**Comment by koron** [comment]
以後の翻訳作業は https://github.com/vim-jp/vimdoc-ja-working のほうでよろしくお願いします。

私はいまから追加でwikiの移植をしてしまいます。
良かったらissueのlabelとかはいじらないつもりですので、
どなたか整えてくれると助かります。

ご協力、ありがとうございました。 :bow:

**Comment by koron** [comment]
wiki のほう、両レポジトリで内容を調整しておきました。
既存の open issue をどうするかは要別途協議ですが、
短いスコープのものはこっちで片付けちゃって、
長いのは向こうへ移す(コピーを作る)くらいが適切かなって考えてます。
