### ISSUE TITLE
i_CTRL-X_CTRL-Y説明文の間違い

### ISSUE THREAD

**Issue by shuei72** [vim-jp/vimdoc-ja#234]
https://github.com/vim-jp/vimdoc-ja/blob/71d9a7b7334be9715a79b057a8e60f53f5b2e2a2/doc/insert.jax#L307
complete_CTRL-Eではなく、complete_CTRL-Yが正しいです。
近くに飛べるのでそれほど困らないですが、一応報告しておきます。

**Comment by crazymaster** [comment]
Thanks!
