### ISSUE TITLE
原文に terminal.txt へのリンクが存在しない

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-ja#240]
左側のメニューに terminal.txt のメニューが存在しません。

この部分は `:help` の `doc-file-list` を基に `_layout/vimdoc.html` に手で記述しています。
しかし `doc-file-list` に terminal.txt へのリンクがないために左側のメニューにもない状態です。

面白くないので `特定機能` (`Special issues`) の最後にこっそり追加しておきます。
正式に対応・追加された暁には修正をしてください。

**Comment by k-takata** [comment]
そういえば、ft_rust.txt も無かった気がします。

**Comment by k-takata** [comment]
原文が更新されたので、それに合わせて修正しました。
