### ISSUE TITLE
[CSS / デザイン] "📝編集" ボタンがイケてないのを直す

### ISSUE THREAD

**Issue by ujihisa** [vim-jp/vimdoc-ja#243]
## Problems

https://github.com/vim-jp/vimdoc-ja/pull/242 でマージした編集ボタンの2つの問題:

* 全然言語関係ないのに `<span class="EnglishJapaneseLink">` 内にある (なんか別のとこのがよさそう)
* リンク先に飛んだgithubでは "📝編集" ではなく以下のようにあるので見た目の乖離があって直感に反するきがする

githubではこんな感じ

<img width="106" alt="2018-06-13 19 48 46" src="https://user-images.githubusercontent.com/11504/41347434-9ea86dd0-6f44-11e8-9b27-fc2e9d53381a.png">

## (Possible) solutions

ユーザから見て直感的なら基本的にどんなやり方でもいい。githubのやつと似てる画像用意して、それを良い感じに貼ってやるといいかも。
ゴールは「ドキュメントにおかしいとこあるとき、読者がかなり気軽にそれを編集できる」というもの。

https://qiita.com/amay077/items/8823376f307235a7f651 この記事が参考になる

**Comment by crazymaster** [comment]
githubと同じものを使いたかったらこれでいけると思います
https://octicons.github.com/icon/pencil/

**Comment by heavenshell** [comment]
<img width="402" alt="2018-06-14 2 09 29" src="https://user-images.githubusercontent.com/56591/41366741-05799a1a-6f78-11e8-8d47-e5a3d25fcd2c.png">

こんな感じになるっぽいですね。

**Comment by ujihisa** [comment]
https://github.com/primer/octicons#license MITライセンスなので、この画像を使うときは、「著作権表示」「MITライセンスの全文 OR MITライセンスの全文が記載されているウェブページのURL」を載せれば使えそう!

**Comment by mattn** [comment]
mac 持ってないのでどなたか記事のキャプチャ更新して頂けると助かる。

**Comment by ujihisa** [comment]
期待

**Comment by heavenshell** [comment]
対応済みなので close します。

**Comment by ujihisa** [comment]
文明開化
