### ISSUE TITLE
README.md の修正が(意図せず？)revertされている

### ISSUE THREAD

**Issue by mnishz** [vim-jp/vimdoc-ja#248]
vimdoc-ja-working から merge される仕組みを私がきちんと理解していないので、もし間違っていたらすみません。
vimdoc-ja の README.md についてですが、2018/06/18付けの最新の merge (755c4e2e5280a5a0c248a3caff6dc3606d1ae637) で、
一つ前の @k-takata さんの 15502fb の変更が先祖返りしてしまっているように見えます。
もし意図しない状態になっていたらと思いコメントいたしました。
ご確認いただけると助かります。

**Comment by h-east** [comment]
これ https://github.com/vim-jp/vimdoc-ja/commit/15502fb984c78323680a2ee237e0d3a540eaaa59 はvimdoc-ja-workingのREADME.mdを修正するべきだった ってことかと思います。

**Comment by k-takata** [comment]
しまった、vimdoc-ja-working の README-dist.md を修正しないといけないのでした。
完全に忘れてた。

**Comment by mnishz** [comment]
あ、なるほど。.travis.yml の仕組みを勉強をすればこのあたりの仕組みが分かるんですかね。
とりあえず、無駄死に issue ではなかったようでよかったです。。。
こちらは変更なしで close して vimdoc-ja-working のほうで修正することになりますかね。

**Comment by k-takata** [comment]
帰ったら直す予定。
vimdoc-ja-working に入れる修正コミットで、こちらを一緒に閉じることもできます。

**Comment by mnishz** [comment]
そうですか、では close もお願いいたします。どうやってやるのか興味があるので。
(単に人力で close という意味だったらすみません。。)

**Comment by k-takata** [comment]
コミットメッセージに `Fix #248` などと書いて master にプッシュすれば、同じリポジトリの該当するissueがクローズされますが、代わりに `Fix vim-jp/vimdoc-ja#248` などと書けば、権限のある別リポジトリのissueをクローズすることができます。
