### ISSUE TITLE
Typo in popup.txt

### ISSUE THREAD

**Issue by skanehira** [vim-jp/vimdoc-ja#256]
ポップアップウィンドウのfunction名が間違っています。
`:h popup-functions`

誤：`popup_notifiation()`
正：`popup_notification()`

![image](https://user-images.githubusercontent.com/7888591/59557538-27ecf900-9017-11e9-99e4-41e535447df2.png)

**Comment by h-east** [comment]
Thanks:+1:
本家のtypoは下記のissueに差分を貼り付ける形でお願いします。
https://github.com/vim-jp/issues/issues/1172
今回はこちらで対応しましたのでこのissueは閉じますね。
