### ISSUE TITLE
mkdir()の{prot}の例に間違いが有る

### ISSUE THREAD

**Issue by iranoan** [vim-jp/vimdoc-ja#266]
記載の待ちが愛の報告もこちらで良いのでしょうか?

修正内容としては、タイトル通りで
0o755→0755
0o700→0700
が必要です

**Comment by k-takata** [comment]
`0o755` で合っています。vimdoc-ja はできるだけ最新のヘルプに追従しようとしていますので、Vim 本体が古いとヘルプ通りの動作をしないことがあります。

`0o` 記法の 8 進数表記は 8.2.0886 で追加されたのですが、`0o0755` なら OK だが `0o755` だとエラーになるバグがありました。8.2.2309 で `0o755` も正しく 8 進数として解釈されるようになりました。
そのため 8.2.2309 以降を使えばヘルプの記載通りに動作するはずです。

**Comment by iranoan** [comment]
私が使っているので、ディストリビューション公式の 8.2.0716 なのが原因だったんですね
お騒がせしました
