### ISSUE TITLE
Fails update vimdoc-ja(using lazy.nvim)

### ISSUE THREAD

**Issue by mimikun** [vim-jp/vimdoc-ja#279]
Sometimes updating vimdoc-ja fails.

```txt
Failed (1)
  󰊠 vimdoc-ja  h (c)
      You have local changes in `/home/username/.local/share/nvim/site/lazy/vimdoc-ja`:
        * doc/tags-ja
      Please remove them to update.
      You can also press `x` to remove the plugin and then `I` to install it again.
```

I need to uninstall and reinstall again.
It's very troublesome.

### env

- neovim: nightly
- lazy.nvim: latest
- OS:
    - Windows: Windows 11 Pro 22H2
    - Ubuntu: 22.04(WSL2)

#### Windows

```txt
エディション	Windows 11 Pro
バージョン	22H2
インストール日	‎2022/‎09/‎21
OS ビルド	22621.2500
エクスペリエンス	Windows Feature Experience Pack 1000.22677.1000.0
```

#### neovim

```shell
❯ nvim -V1 -v
NVIM v0.10.0-dev-bc850ba
Build type: RelWithDebInfo
LuaJIT 2.1.1697887905
Compilation: /usr/bin/gcc-10 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99
-Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/home/runner/work/neovim/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/runner/work/neovim/neovim/.deps/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by k-takata** [comment]
Whether to include `doc/tags-ja` in the repository was discussed before: https://github.com/vim-jp/vimdoc-ja-working/issues/268

At that time, we decided to include it because Vim's help recommends to do so.
But, this kind of issue has been reported several times: e.g. https://github.com/vim-jp/vimdoc-ja-working/issues/1206
We might need to reconsider it?
(I hope plugin managers handle this correctly, though.)

**Comment by mimikun** [comment]
As far as I've researched, there are only a limited number of plugin managers that address this issue.
- neovim: pckr.nvim
Is it possible to solve this by creating a branch (e.g. `release`) for installation with the plugin manager and setting it to ignore `doc/tags-ja` there?

**Comment by Shougo** [comment]
Both dein.vim and dpp.vim also don't have the problem.

**Comment by h-east** [comment]
All Vim plugin managers that run `:helptags` unconditionally have this problem.
First of all, it is bad behavior for the plugin manager to unconditionally update the plugin's distribution file.

Vim plugin manager need to check the timestamp like [minpac](https://github.com/k-takata/minpac) or add a judgment like [this](https://gist.github.com/h-east/5c304b578bd36a17dca84af7598fd921).

**Comment by mimikun** [comment]
Unfortunately, there are more "bad behavior" plugins than "good behavior" plugins.

## good behavior plugins
- [Shougo/dein.vim](https://github.com/Shougo/dein.vim) (Unmainteined)
- [Shougo/dpp.vim](https://github.com/Shougo/dpp.vim)
- [k-takata/minpac](https://github.com/k-takata/minpac)
- [lewis6991/pckr.nvim](https://github.com/lewis6991/pckr.nvim)
	- https://github.com/lewis6991/pckr.nvim/blob/40c4193c83ef17a9cf38514b93a2332955789581/lua/pckr/actions.lua#L63
- [wbthomason/packer.nvim](https://github.com/wbthomason/packer.nvim) (Unmainteined)
	- https://github.com/wbthomason/packer.nvim/blob/ea0cc3c59f67c440c5ff0bbe4fb9420f4350b9a3/lua/packer/plugin_utils.lua#L60

## bad behavior plugins
- [folke/lazy.nvim](https://github.com/folke/lazy.nvim)
	- https://github.com/folke/lazy.nvim/discussions/925
- [junegunn/vim-plug](https://github.com/junegunn/vim-plug)
	- https://github.com/junegunn/vim-plug/pull/773
- [tani/vim-jetpack](https://github.com/tani/vim-jetpack)
- [tpope/vim-pathogen](https://github.com/tpope/vim-pathogen)
- [savq/paq-nvim](https://github.com/savq/paq-nvim)
- [VundleVim/Vundle.vim](https://github.com/VundleVim/Vundle.vim)
- [ii14/neopm](https://github.com/ii14/neopm)
- [chiyadev/dep](https://github.com/chiyadev/dep)
- [notomo/optpack.nvim](https://github.com/notomo/optpack.nvim)
- [rktjmp/pact.nvim](https://github.com/rktjmp/pact.nvim)

**Comment by folke** [comment]
The reason that plugin managers like lazy generate doc tags for installed/updated plugins, is that 99% of the plugins **do not provide** doc tags, or ship outdated doc tags.

`vimdoc-ja` is in the minority here.

It's also a bad idea to put doc/tags under version control, since they don't really seem to be idempotent.

I'm not planning to add any kind of exceptions for plugin managed doc tags to lazy.nvim

**Comment by mimikun** [comment]
I was able to avoid this issue by implementing a workaround based on https://github.com/delphinus/dotfiles/blob/master/.config/nvim/lua/core/lazy/init.lua.

https://github.com/mimikun/dotfiles/blob/b724b47d8ac92cf9098effdd6cbd60447baffc5e/dot_config/nvim/lua/plugins/vimdoc-ja.lua#L3-L21

Thank you!

**Comment by h-east** [comment]
@mimikun Hmm, Isn't this problem solved by merging the PR below?
https://github.com/vim-jp/vimdoc-ja-working/pull/1434

**Comment by h-east** [comment]
It has already been reflected.
