### ISSUE TITLE
文体が統一されていない

### ISSUE THREAD

**Issue by thinca** [vim-jp/vimdoc-ja#5]
恐らく歴史的経緯でこうなっていて、労力の関係で放置されているものと思われますが、実際にやるかどうかは別としてIssueとして登録しておきます。
ここでは、統一するとしたらどの方向に統一すべきか議論できれば、と思います。決まったことは Wiki にまとめましょう。

**Comment by k-takata** [comment]
https://github.com/vim-jp/vimdoc-ja-working/issues/1799 にて継続。こちらは閉じます。
