### ISSUE TITLE
オプション表記 'hoge' の直前に'('等がある場合に<C-]>やマウスダブルクリックで飛べなくなっている

### ISSUE THREAD

**Issue by h-east** [vim-jp/vimdoc-ja#89]
前からなのか途中で変わったのか調べてないんですが、オプション表記 'hoge' の直前に空白以外のprintableな文字(0x21～0x7e)があると<C-]>やマウスダブルクリックで飛べなくなっています。
本家doc&vimdoc-ja両方で修正が必要なもの、vimdoc-jaでのみ修正が必要なものあります。
前者は洗い出してvim_devに報告しないといけなさそう。

前者の例:
`:h arabic.txt` または `:h arabic.txt@ja` して `/('rl/e` して `<C-]>`
E149: Sorry, no help for ('rl'

後者の例:
`:h 'fo'@ja` して `/('fo/e` して `<C-]>`
E149: Sorry, no help for ('formatoptions'

---

そこそこ多そう

```
:vimgrep "\W('\w\{2,}" $VIMRUNTIME/doc/*
```

kaoriya版は以下も検索

```
:vimgrep "\W('\w\{2,}" $VIM/plugins/vimdoc-ja/doc/*
```

---

何故か後ろに ')' があっても飛べてしまう。あれ？どうなっとるん？？
`:h fex` または `:h fex@ja` して `/ons')` して `<C-]>`
→飛べて:horse:しまうま

`h: file-searching@ja` して `/path')` して `<C-]>`
→飛べて:horse:しまうま2

ということでご意見、情報お待ちしてます。

**Comment by h-east** [comment]
> 何故か後ろに ')' があっても飛べてしまう。あれ？どうなっとるん？？

:helpの場合、`'`で始まるパターンは次の`'`までをタグとしてタグ検索する。だから大丈夫なのであった。
https://github.com/vim/vim/blob/master/src/ex_cmds.c#L6197-L6202

**Comment by k-takata** [comment]
Vim本体は7.4.1604で直っており、ヘルプも修正済みなので閉じます。
